# Generated by Django 6.0.5 on 2026-06-02 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("queue_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="counter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operators",
                to="queue_app.counter",
            ),
        ),
    ]
