# Generated by Django 6.0.5 on 2026-06-04 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_counter"),
        (
            "catalog",
            "0003_hall_alter_servicecategory_code_servicecategory_hall_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hall",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff",
                to="catalog.hall",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("chief_admin", "Chief administrator"),
                    ("hall_admin", "Hall administrator"),
                    ("operator", "Operator"),
                    ("viewer", "Viewer"),
                ],
                default="operator",
                max_length=16,
            ),
        ),
    ]
