# Generated by Django 6.0.5 on 2026-06-02 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=4, unique=True)),
                ("name_kaa", models.CharField(max_length=255)),
                ("name_ru", models.CharField(max_length=255)),
                ("color", models.CharField(max_length=9)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "service categories",
                "ordering": ["order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_kaa", models.CharField(max_length=512)),
                ("name_ru", models.CharField(max_length=512)),
                ("sla_days", models.PositiveIntegerField(default=0)),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[
                            ("electron", "Electron"),
                            ("qagaz", "Qagaz"),
                            ("awizeki", "Awizeki"),
                            ("electron_qagaz", "Electron Qagaz"),
                            ("electron_awizeki", "Electron Awizeki"),
                            ("jiynalmali_papka", "Jiynalmali Papka"),
                        ],
                        max_length=32,
                    ),
                ),
                ("requires_visit", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="catalog.servicecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category__order", "id"],
            },
        ),
    ]
