# Generated by Django 6.0.5 on 2026-06-04 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_service_is_popular"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=8, unique=True)),
                ("name_kaa", models.CharField(max_length=255)),
                ("name_ru", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "code"],
            },
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="code",
            field=models.CharField(max_length=4),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="hall",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="catalog.hall",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicecategory",
            constraint=models.UniqueConstraint(
                fields=("hall", "code"), name="uniq_category_code_per_hall"
            ),
        ),
    ]
