# Generated by Django 6.0.5 on 2026-06-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0003_hall_alter_servicecategory_code_servicecategory_hall_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="hall",
            name="name_en",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="hall",
            name="name_uz",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="service",
            name="name_en",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="service",
            name="name_uz",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="name_en",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="name_uz",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
