# Generated by Django 6.0.5 on 2026-06-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queue_app", "0002_dailycounter_operatorsession_ticket"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisplaySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("youtube_url", models.URLField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Display settings",
                "verbose_name_plural": "Display settings",
            },
        ),
    ]
