# Generated by Django 6.0.5 on 2026-06-04 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0003_hall_alter_servicecategory_code_servicecategory_hall_and_more",
        ),
        ("queue_app", "0003_displaysettings"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dailycounter",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="counter",
            name="hall",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counters",
                to="catalog.hall",
            ),
        ),
        migrations.AddField(
            model_name="dailycounter",
            name="hall",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_counters",
                to="catalog.hall",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="hall",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="catalog.hall",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailycounter",
            unique_together={("hall", "code", "date")},
        ),
    ]
