# Generated by Django 6.0.5 on 2026-06-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queue_app", "0005_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
