# Generated by Django 6.0.5 on 2026-06-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queue_app", "0006_ticket_finished_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="operatorsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
