# Generated by Django 6.0.5 on 2026-06-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queue_app", "0007_operatorsession_updated_at_ticket_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="displaysettings",
            name="org_name",
            field=models.CharField(
                blank=True, default="Ájiniyaz atındaǵı NMPI", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="displaysettings",
            name="ticker_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="displaysettings",
            name="voice_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="displaysettings",
            name="voice_lang",
            field=models.CharField(default="ru-RU", max_length=8),
        ),
    ]
