# Generated by Django 6.0.5 on 2026-06-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queue_app", "0009_workschedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tickets_wm", models.DateTimeField(blank=True, null=True)),
                ("sessions_wm", models.DateTimeField(blank=True, null=True)),
                ("audit_wm_id", models.PositiveIntegerField(default=0)),
                ("catalog_pulled_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
