# Generated by Django 6.0.5 on 2026-06-22 13:19

import queue_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queue_app", "0010_syncstate"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceClip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("letter", "letter"),
                            ("num", "num"),
                            ("window", "window"),
                        ],
                        max_length=8,
                    ),
                ),
                ("key", models.CharField(max_length=8)),
                ("file", models.FileField(upload_to=queue_app.models.voice_clip_path)),
                ("enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["kind", "key"],
                "unique_together": {("kind", "key")},
            },
        ),
    ]
